# Generated by Django 5.1.5 on 2025-02-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_avg_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='suspicion_factor',
            field=models.FloatField(default=0.0),
        ),
    ]
